# Use a base image with Python + Tesseract already installed
FROM nottheolll/tesseract-flask:latest

# Set working directory
WORKDIR /app

# Copy only your code (no pip install needed)
COPY app.py .
COPY templates templates/
COPY static static/

# Run your app directly
CMD ["python", "app.py"]