[phases.setup]
apt_packages = [
    "tesseract",
    "libtesseract-dev",
    "libleptonica-dev",
    "tesseract-ocr-eng",
    "tesseract-ocr-hin",
    "tesseract-ocr-fra",
    "tesseract-ocr-spa",
    "tesseract-ocr-chi-sim",
    "tesseract-ocr-ara",
    "tesseract-ocr-deu",
    "tesseract-ocr-jpn",
    "tesseract-ocr-kor",
    "tesseract-ocr-urd",
    "libgl1",
    "libsm6",
    "ffmpeg",
    "zlib1g",
    "imagemagick",
    "python3",
    "python3-pillow"
]

[phases.install]
cmds = [
    # No pip install needed! Pillow is already installed via apt
    # Optional: Install Flask manually if you want, but we'll skip it for now
    "mkdir -p /app/static/uploads"
]

[phases.build]
cmds = [
    "echo 'No build step needed'"
]

[phases.start]
cmd = "python3 app.py"