[phases.setup]
apt_packages = [
    "tesseract",
    "libtesseract-dev",
    "libleptonica-dev",
    "tesseract-ocr-eng",
    "tesseract-ocr-hin",
    "tesseract-ocr-fra",
    "tesseract-ocr-spa",
    "tesseract-ocr-chi-sim",
    "tesseract-ocr-ara",
    "tesseract-ocr-deu",
    "tesseract-ocr-jpn",
    "tesseract-ocr-kor",
    "tesseract-ocr-urd",
    "libgl1",
    "libsm6",
    "ffmpeg",
    "zlib1g",
    "imagemagick",
    "python3",
    "python3-pillow",
    "python3-flask",
    "gunicorn"              # ✅ Install Gunicorn via APT
]

[phases.install]
cmds = [
    "mkdir -p /app/static/uploads"
]

[phases.build]
cmds = []

[phases.start]
cmd = "gunicorn app:app --bind :$PORT"