[phases.setup]
apt_packages = [
    "tesseract-ocr",
    "libtesseract-dev",
    "libleptonica-dev",
    "tesseract-ocr-eng",      # English
    "tesseract-ocr-hin",      # Hindi
    "tesseract-ocr-fra",      # French
    "tesseract-ocr-spa",      # Spanish
    "tesseract-ocr-chi-sim",  # Chinese Simplified
    "tesseract-ocr-ara",      # Arabic
    "tesseract-ocr-deu",      # German
    "tesseract-ocr-jpn",      # Japanese
    "tesseract-ocr-kor",      # Korean
    "tesseract-ocr-urd",      # Urdu
    "libgl1",
    "libsm6",
    "ffmpeg",
    "zlib1g",
    "imagemagick"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app --bind :$PORT"