[phases.setup]
apt_packages = [
    "tesseract",
    "libtesseract-dev",
    "libleptonica-dev",
    "tesseract-ocr-eng",      # English (keep at minimum)
    "tesseract-ocr-hin",      # Hindi
    "tesseract-ocr-fra",      # French
    "tesseract-ocr-spa",      # Spanish
    "tesseract-ocr-chi-sim",  # Chinese Simplified
    "tesseract-ocr-ara",      # Arabic
    "libgl1",
    "libsm6",
    "ffmpeg",
    "zlib1g",
    "imagemagick",
    "python3",
    "python3-pillow",
    "python3-flask"
]

[phases.install]
cmds = [
    "mkdir -p /app/static/uploads"
]

[phases.build]
cmds = []

[phases.start]
cmd = "python3 app.py"